/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddProductRouteImport } from './routes/add-product'
import { Route as ClaimCheckupRouteImport } from './routes/claim-checkup'
import { Route as MissingEvidenceRouteImport } from './routes/missing-evidence'
import { Route as PassportRouteImport } from './routes/passport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddProductRoute = AddProductRouteImport.update({
  id: '/add-product',
  path: '/add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimCheckupRoute = ClaimCheckupRouteImport.update({
  id: '/claim-checkup',
  path: '/claim-checkup',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingEvidenceRoute = MissingEvidenceRouteImport.update({
  id: '/missing-evidence',
  path: '/missing-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-product': typeof AddProductRoute
  '/claim-checkup': typeof ClaimCheckupRoute
  '/missing-evidence': typeof MissingEvidenceRoute
  '/passport': typeof PassportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-product': typeof AddProductRoute
  '/claim-checkup': typeof ClaimCheckupRoute
  '/missing-evidence': typeof MissingEvidenceRoute
  '/passport': typeof PassportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-product': typeof AddProductRoute
  '/claim-checkup': typeof ClaimCheckupRoute
  '/missing-evidence': typeof MissingEvidenceRoute
  '/passport': typeof PassportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/add-product' | '/claim-checkup' | '/missing-evidence' | '/passport'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/add-product' | '/claim-checkup' | '/missing-evidence' | '/passport'
  id:
    | '__root__'
    | '/'
    | '/add-product'
    | '/claim-checkup'
    | '/missing-evidence'
    | '/passport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddProductRoute: typeof AddProductRoute
  ClaimCheckupRoute: typeof ClaimCheckupRoute
  MissingEvidenceRoute: typeof MissingEvidenceRoute
  PassportRoute: typeof PassportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-product': {
      id: '/add-product'
      path: '/add-product'
      fullPath: '/add-product'
      preLoaderRoute: typeof AddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-checkup': {
      id: '/claim-checkup'
      path: '/claim-checkup'
      fullPath: '/claim-checkup'
      preLoaderRoute: typeof ClaimCheckupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missing-evidence': {
      id: '/missing-evidence'
      path: '/missing-evidence'
      fullPath: '/missing-evidence'
      preLoaderRoute: typeof MissingEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddProductRoute: AddProductRoute,
  ClaimCheckupRoute: ClaimCheckupRoute,
  MissingEvidenceRoute: MissingEvidenceRoute,
  PassportRoute: PassportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
