/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddProductRouteImport } from './routes/add-product'
import { Route as CaseFileRouteImport } from './routes/case-file'
import { Route as ClaimCheckupRouteImport } from './routes/claim-checkup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MissingEvidenceRouteImport } from './routes/missing-evidence'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UploadProofRouteImport } from './routes/upload-proof'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddProductRoute = AddProductRouteImport.update({
  id: '/add-product',
  path: '/add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseFileRoute = CaseFileRouteImport.update({
  id: '/case-file',
  path: '/case-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimCheckupRoute = ClaimCheckupRouteImport.update({
  id: '/claim-checkup',
  path: '/claim-checkup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingEvidenceRoute = MissingEvidenceRouteImport.update({
  id: '/missing-evidence',
  path: '/missing-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadProofRoute = UploadProofRouteImport.update({
  id: '/upload-proof',
  path: '/upload-proof',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-product': typeof AddProductRoute
  '/case-file': typeof CaseFileRoute
  '/claim-checkup': typeof ClaimCheckupRoute
  '/login': typeof LoginRoute
  '/missing-evidence': typeof MissingEvidenceRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/upload-proof': typeof UploadProofRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-product': typeof AddProductRoute
  '/case-file': typeof CaseFileRoute
  '/claim-checkup': typeof ClaimCheckupRoute
  '/login': typeof LoginRoute
  '/missing-evidence': typeof MissingEvidenceRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/upload-proof': typeof UploadProofRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-product': typeof AddProductRoute
  '/case-file': typeof CaseFileRoute
  '/claim-checkup': typeof ClaimCheckupRoute
  '/login': typeof LoginRoute
  '/missing-evidence': typeof MissingEvidenceRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/upload-proof': typeof UploadProofRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-product'
    | '/case-file'
    | '/claim-checkup'
    | '/login'
    | '/missing-evidence'
    | '/passport'
    | '/profile'
    | '/scan'
    | '/signup'
    | '/upload-proof'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-product'
    | '/case-file'
    | '/claim-checkup'
    | '/login'
    | '/missing-evidence'
    | '/passport'
    | '/profile'
    | '/scan'
    | '/signup'
    | '/upload-proof'
  id:
    | '__root__'
    | '/'
    | '/add-product'
    | '/case-file'
    | '/claim-checkup'
    | '/login'
    | '/missing-evidence'
    | '/passport'
    | '/profile'
    | '/scan'
    | '/signup'
    | '/upload-proof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddProductRoute: typeof AddProductRoute
  CaseFileRoute: typeof CaseFileRoute
  ClaimCheckupRoute: typeof ClaimCheckupRoute
  LoginRoute: typeof LoginRoute
  MissingEvidenceRoute: typeof MissingEvidenceRoute
  PassportRoute: typeof PassportRoute
  ProfileRoute: typeof ProfileRoute
  ScanRoute: typeof ScanRoute
  SignupRoute: typeof SignupRoute
  UploadProofRoute: typeof UploadProofRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-product': {
      id: '/add-product'
      path: '/add-product'
      fullPath: '/add-product'
      preLoaderRoute: typeof AddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-file': {
      id: '/case-file'
      path: '/case-file'
      fullPath: '/case-file'
      preLoaderRoute: typeof CaseFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-checkup': {
      id: '/claim-checkup'
      path: '/claim-checkup'
      fullPath: '/claim-checkup'
      preLoaderRoute: typeof ClaimCheckupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missing-evidence': {
      id: '/missing-evidence'
      path: '/missing-evidence'
      fullPath: '/missing-evidence'
      preLoaderRoute: typeof MissingEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-proof': {
      id: '/upload-proof'
      path: '/upload-proof'
      fullPath: '/upload-proof'
      preLoaderRoute: typeof UploadProofRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddProductRoute: AddProductRoute,
  CaseFileRoute: CaseFileRoute,
  ClaimCheckupRoute: ClaimCheckupRoute,
  LoginRoute: LoginRoute,
  MissingEvidenceRoute: MissingEvidenceRoute,
  PassportRoute: PassportRoute,
  ProfileRoute: ProfileRoute,
  ScanRoute: ScanRoute,
  SignupRoute: SignupRoute,
  UploadProofRoute: UploadProofRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
